name: "Hello Actions"
description: "Greeting someone"
author: "zyycode@github.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
